import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class KnappPanel extends JPanel implements ActionListener {


	private int radie = 5;

	public KnappPanel() {
		KnappButton knapp = new KnappButton();
		add(knapp);
		knapp.addActionListener(this);
	}

	/**
	* Handles ActionEvents
	* @param e An ActionEvent generated by Java.
	*/

	public void actionPerformed(ActionEvent e) {
//		System.out.println("klick");
		radie += 5;
		revalidate();
		repaint();
	}

	public void paint(Graphics g) {
		Toolkit.getDefaultToolkit().sync();
		int x = getWidth()/2;
		int y = getHeight()/2;
		g.setColor(Color.red);
		g.fillOval(x-radie, y-radie, 2*radie, 2*radie);
	}

}